### PR TITLE
feat: add asciidoc

### PR DESCRIPTION
**Pull request by gcusnieux**
Hello, I wanted to add asciidoc with the new format but it's not so easy. 
In the meantime, can we add the old support here ?

### CODE REVIEW

**Comment by marijnh** [comment]
Where is this old support from? The CM5 distribution doesn't come with an ASCIIDoc mode.

**Comment by gcusnieux** [comment]
It comes from https://github.com/asciidoctor/codemirror-asciidoc

**Comment by marijnh** [comment]
Right. I don't want to increase the amount of legacy modes I am maintaining, so the suggested way forward with this is to set up a separate package for this, and publish it to npm yourself.

**Comment by gcusnieux** [comment]
ok no worries I understand.
Do you have any advice on what to use to make something clean for CM6?
Lezer grammar? Tokenizer or Custom parser?
Thx

**Comment by marijnh** [comment]
I don't think ASCIIDocs can be parsed with an LR grammar. If you have a lot of resources for this, doing a manually-written incremental parser like the Lezer Markdown parser would work, but probably just porting the CM5 asciidoc mode to work with `@codemirror/stream-parser` is the most direct way to get something working.

**Pull request closed without merging**
